src/MyStore.Web/Models/UserData.cs
using Newtonsoft.Json;

namespace MyStore.Web.Models
{
    public class UserData
    {
        public int Id { get; set; }
        [JsonProperty("first_name")] public string FirstName { get; set; }
        [JsonProperty("last_name")] public string LastName { get; set; }
    }
}

src/MyStore.Web/Controllers/AccountController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyStore.Infrastructure.Auth;
using MyStore.Services;

namespace MyStore.Web.Controllers
{
    public class AccountController : BaseController
    {
        private readonly IJwtService _jwtService;

        public AccountController(IDispatcher dispatcher,
            IJwtService jwtService) : base(dispatcher)
        {
            _jwtService = jwtService;
        }

        [HttpGet]
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
        public ActionResult<string> Get()
        {
            return HttpContext.User.Identity.Name;
        }

        [HttpPost("login")]
        public async Task<ActionResult<JsonWebToken>> Login()
        {
            var jwt = _jwtService.Create(Guid.NewGuid().ToString(), "user1", "user", null);

            return await Task.FromResult(jwt);
        }
    }
}

src/MyStore.Web/Controllers/BaseController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyStore.Services;

namespace MyStore.Web.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public abstract class BaseController : Controller
    {
        private readonly IDispatcher _dispatcher;

        public BaseController(IDispatcher dispatcher)
        {
            _dispatcher = dispatcher;
        }

        protected ActionResult<T> Result<T>(T result)
        {
            if (result == null)
            {
                return NotFound();
            }

            return result;
        }

        protected Guid UserId => Guid.Parse(HttpContext.User.Claims.Single(c => c.Type == "userId").Value);

        protected async Task SendAsync<T>(T command) where T : ICommand
            => await _dispatcher.SendAsync(command);

        protected async Task<TResult> QueryAsync<TResult>(IQuery<TResult> query)
            => await _dispatcher.QueryAsync(query);
    }
}

src/MyStore.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using MyStore.Services;

namespace MyStore.Web.Controllers
{
    [Route("api")]
    public class HomeController : BaseController
    {
        private readonly IOptions<AppOptions> _appOptions;

        public HomeController(IDispatcher dispatcher,
            IOptions<AppOptions> appOptions) : base(dispatcher)
        {
            _appOptions = appOptions;
        }

        public ActionResult<string> Get() => _appOptions.Value.Name;
    }
}

src/MyStore.Web/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyStore.Services;
using MyStore.Services.Products.Commands;
using MyStore.Services.Products.Dto;
using MyStore.Services.Products.Queries;

namespace MyStore.Web.Controllers
{
    public class ProductsController : BaseController
    {
        public ProductsController(IDispatcher dispatcher) : base(dispatcher)
        {
        }

        [HttpGet]
        public async Task<ActionResult<IEnumerable<ProductDto>>> Get([FromQuery] BrowseProducts query)
            => Result(await QueryAsync(query));

        [HttpGet("{id:guid}")]
        public async Task<ActionResult<ProductDto>> Get(Guid id)
            => Result(await QueryAsync(new GetProduct {Id = id}));

        [HttpPost]
        [Authorize(Policy = "is-admin")]
        public async Task<ActionResult> Post(CreateProduct command)
        {
            await SendAsync(command);

            return CreatedAtAction(nameof(Get), new {id = command.Id}, null);
        }
    }
}

src/MyStore.Web/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyStore.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/MyStore.Web/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyStore.Web.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

src/MyStore.Web/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyStore.Web.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
            throw new ArgumentException("Ooopsss...");
        }
    }
}

src/MyStore.Web/Pages/Products/Details.cshtml.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyStore.Services.Products;
using MyStore.Services.Products.Dto;
using MyStore.Web.Framework;
using MyStore.Web.Models;

namespace MyStore.Web.Pages.Products
{
    public class DetailsModel : PageModel
    {
        private readonly IProductService _productService;
        
        public ProductDto Product { get; private set; }

        public DetailsModel(IProductService productService)
        {
            _productService = productService;
        }

        public async Task<IActionResult> OnGetAsync(Guid id)
        {
            Product = await _productService.GetAsync(id);
            if (Product == null)
            {
                return NotFound();
            }

            return Page();
        }
    }
}

src/MyStore.Web/Pages/Products/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyStore.Services.Products;
using MyStore.Services.Products.Dto;
using MyStore.Web.Framework;
using MyStore.Web.Models;

namespace MyStore.Web.Pages.Products
{
    public class IndexModel : PageModel
    {
        private readonly IProductService _productService;

        public IEnumerable<ProductDto> Products { get; private set; }

        public IEnumerable<SelectListItem> Categories => new List<SelectListItem>
        {
            new SelectListItem("Phones", "Phones"),
            new SelectListItem("Computers", "Computers"),
        };
        
        [BindProperty]
        public ProductDto Product { get; set; } = new ProductDto();

        public IndexModel(IProductService productService)
        {
            _productService = productService;
        }
        
        public async Task OnGetAsync()
        {
            Products = await _productService.BrowseAsync();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            Product.Id = Guid.NewGuid();
            await _productService.AddAsync(Product);

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostDeleteAsync(Guid id)
        {
            await _productService.DeleteAsync(id);
            
            return RedirectToPage();
        }
    }
}

src/MyStore.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/MyStore.Web/Pages/Products/Details.cshtml
@page "/products/{id:guid}"
@model DetailsModel
@{
}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">@Model.Product.Name</h5>
                <h6 class="card-subtitle mb-2 text-muted">@Model.Product.Category</h6>
                <p class="card-text">@Model.Product.Price PLN</p>
            </div>
        </div>
    </div>
</div>

src/MyStore.Web/Pages/Products/Index.cshtml
@page
@model IndexModel
@{
}

<div class="row">
    @foreach (var product in Model.Products)
    {
        <div class="col-lg-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"><a asp-page="./Details" asp-route-id="@product.Id">@product.Name</a></h5>
                    <h6 class="card-subtitle mb-2 text-muted">@product.Category</h6>
                    <p class="card-text">@product.Price PLN</p>
                    <form method="post">
                        <button type="submit" class="btn btn-danger"
                                asp-page-handler="delete"
                                asp-route-id="@product.Id">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    }
</div>

<hr/>

<h3>Create product</h3>
<div class="row">
    <div class="col-lg-12">
        <form method="post">
            <div class="form-group">
                <label asp-for="Product.Name"></label>
                <input asp-for="Product.Name" class="form-control"/>
                <span asp-validation-for="Product.Name"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.Price"></label>
                <input asp-for="Product.Price" class="form-control"/>
                <span asp-validation-for="Product.Price"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.Category"></label>
                <select asp-for="Product.Category" asp-items="Model.Categories" class="form-control"></select>
                <span asp-validation-for="Product.Category"></span>
            </div>
            <input type="submit" class="btn btn-success" value="Create"/>
        </form>
    </div>
</div>

src/MyStore.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyStore.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">MyStore.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Products/Index">Products</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2018 - MyStore.Web - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.0.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>

<environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>